import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

const AppSettingsContext = createContext();

const translations = {
  en: {
    /* Common */
    help: "Help",
    listProperty: "List your property",
    register: "Register",
    signIn: "Sign In",
    navHelp: "Help",
    navListProperty: "List your property",
    navRegister: "Register",
    navSignIn: "Sign In",
    logout: "Logout",
    home: "Home",
    dashboard: "Dashboard",
    viewAll: "View all",
    verified: "Verified",
    excellent: "Excellent",
    reviews: "reviews",
    needHelp: "Need help?",
    contactSupport: "Contact Support",

    /* Search/Common Form */
    destination: "Destination",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Guests",
    search: "Search",
    checkAvailability: "Check Availability",

    /* Home */
    heroBadge: "Explore • Book • Experience",
    heroTitle: "Find hotels and plan your Sri Lanka trip in one place",
    heroSubtitle:
      "Search by destination or hotel name. Compare stays, discover experiences, and book faster.",
    popularDestinations: "Popular Destinations in Sri Lanka",
    popularDestinationsSub: "Start your journey with the most searched cities.",
    exploreHotels: "Explore Hotels",
    popular: "Popular",
    beach: "Beach",
    cultural: "Cultural",
    nature: "Nature",
    luxury: "Luxury",
    budget: "Budget",
    festivals: "Festivals",

    /* Results */
    searchResults: "Search Results",
    staysFound: "stays found",
    filterBy: "Filter by",
    reset: "Reset",
    priceRange: "Price range per night",
    popularFilters: "Popular filters",
    verifiedOnly: "Verified hotels only",
    viewDetails: "View details",
    showing: "Showing",
    hotels: "hotels",
    sortBy: "Sort by",
    recommended: "Recommended",

    /* Hotel Details */
    overview: "Overview",
    rooms: "Rooms",
    dine: "Dine",
    events: "Events",
    policies: "Policies",
    contact: "Contact",
    bestSeller: "Best seller in",
    pendingVerification: "Pending Verification",
    reviewText: "reviews",
    topRatedStay: "Top-rated stay",
    topRatedDesc: "Guests love this hotel for comfort and location.",
    payAtHotel: "Pay at hotel",
    payAtHotelDesc: "Book now and complete payment during check-in.",
    greatLocation: "Great location",
    greatLocationDesc: "Close to attractions, restaurants, and transport.",
    experiencesNearHotel: "Experiences Near This Hotel",
    experiencesDesc: "Discover exciting places and activities nearby.",
    getDirections: "Get directions",
    roomsAvailability: "Rooms & Availability",
    roomsAvailabilityDesc: "Select dates to see available rooms and pricing.",
    viewAllRooms: "View all rooms",
    facilities: "Facilities",
    facilitiesDesc: "Everything you need for a comfortable stay.",
    reserve: "Reserve",
    reserveNow: "Reserve Now",
    startingFrom: "Starting from",
    perNight: "per night",
    perNightForTwo: "per night for 2 adults",
    policiesDesc: "Please read the hotel policies before booking.",
    cancellation: "Cancellation",
    cancellationDesc: "Free cancellation before selected policy deadline.",
    payment: "Payment",
    paymentDesc: "Pay at hotel option available for demo booking.",
    showOnMap: "Show on map",
    noBookingFees: "No booking fees",
    payAtHotelAvailable: "Pay at hotel available",
    verifiedHotelListing: "Verified hotel listing",
    supportText: "Our support team can help you with bookings and hotel details.",
    selectCheckIn: "Select check-in",
    selectCheckOut: "Select check-out",
    loadingHotel: "Loading hotel details...",

    /* Login */
    loginTitle: "Sign In",
    loginSubtitle: "Enter your account details to continue.",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    createAccount: "Create account",
    welcomeBack: "Welcome back",
    loginHeroTitle: "Sign in and continue your Sri Lanka journey",
    loginHeroSubtitle:
      "Access your bookings, saved hotels, partner dashboard, and admin tools using one secure TourismHub LK account.",
    bookHotelsFaster: "Book Hotels Faster",
    loginBenefitBooking: "Continue your searches and manage reservations easily.",
    secureLogin: "Secure Login",
    secureLoginDesc: "Your account uses role-based access for better safety.",
    exploreSriLanka: "Explore Sri Lanka",
    exploreSriLankaDesc:
      "Discover stays, events, and experiences in one platform.",
    enterPassword: "Enter your password",
    hidePassword: "Hide",
    showPassword: "Show",
    signingIn: "Signing in...",
    demoLoginGuide: "Demo login guide",
    demoLoginGuideDesc:
      "Use the email and password you inserted into your database using registration or Postman.",
    doNotHaveAccount: "Do not have an account?",
    enterEmailPassword: "Please enter your email and password.",
    invalidLogin: "Invalid email or password.",
    loginSuccess: "Login successful. Redirecting...",
    serverConnectionFailed:
      "Cannot connect to server. Please check if backend is running.",

    /* Register */
    registerTitle: "Create Account",
    registerSubtitle: "Fill your details to get started.",
    fullName: "Full Name",
    phone: "Phone Number",
    confirmPassword: "Confirm Password",
    tourist: "Tourist",
    hotelPartner: "Hotel Partner",
    createYourAccount: "Create Your Account",
    registerHeroTitle: "Join TourismHub LK and explore Sri Lanka with ease",
    registerHeroSubtitle:
      "Register as a tourist to book hotels and discover experiences, or join as a hotel partner to list and manage your property.",
    bookHotelsFasterDesc: "Search, compare, and reserve hotels in Sri Lanka.",
    partnerManagement: "Partner Management",
    partnerManagementDesc:
      "Manage rooms, prices, bookings, and hotel content.",
    secureAccess: "Secure Access",
    secureAccessDesc: "Role-based login for tourists, partners, and admins.",
    enterFullName: "Enter your full name",
    agreeTerms: "I agree to Terms",
    creatingAccount: "Creating Account...",
    semesterDemo: "For semester demo",
    semesterDemoDesc:
      "Create a tourist account for hotel search and a partner account for partner dashboard testing.",
    alreadyHaveAccount: "Already have an account?",
    fillAllFields: "Please fill all required fields.",
    passwordMinLength: "Password must be at least 6 characters.",
    passwordMismatch: "Passwords do not match.",
    agreeTermsError: "Please agree to the Terms and Conditions.",
    registrationFailed: "Registration failed. Email may already exist.",
    accountCreatedSuccess:
      "Account created successfully. Redirecting to login...",

    /* Partner Dashboard */
    partnerPortal: "Partner Portal",
    bookings: "Bookings",
    calendar: "Calendar",
    roomsPricing: "Rooms & Pricing",
    promotions: "Promotions",
    management: "Management",
    reports: "Reports",
    hotelPartnerDashboard: "Hotel Partner Dashboard",
    partnerWelcomeText:
      "Here’s what’s happening at your property. Manage bookings, rooms, check-ins, and availability from one place.",
    addRoom: "Add Room",
    editHotel: "Edit Hotel",
    newBookings: "New Bookings",
    upcomingBookings: "3 upcoming",
    todayCheckIns: "Today Check-Ins",
    remainingCheckIns: "5 remaining",
    todayCheckOuts: "Today Check-Outs",
    allCheckedOut: "All checked out",
    availabilityAlert: "Availability Alert",
    roomsNeedAttention: "rooms need attention",
    averageRating: "Average Rating",
    onlyOneRoomLeft: "Only 1 Deluxe Room left",
    latestBookings: "Latest Bookings",
    latestBookingsDesc: "View and manage your latest hotel reservations.",
    showAllBookings: "Show: All Bookings",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    allRooms: "All Rooms",
    searchBookings: "Search bookings...",
    bookingId: "Booking ID",
    guest: "Guest",
    room: "Room",
    dates: "Dates",
    amount: "Amount",
    status: "Status",
    confirmed: "Confirmed",
    pending: "Pending",
    cancelled: "Cancelled",
    noBookingsFound: "No bookings found.",
    growProperty: "Grow your property",
    improveListingTitle: "Improve your listing and attract more travelers",
    improveListingDesc:
      "Add better photos, update room prices, and keep availability accurate to increase bookings.",
    updateListing: "Update Listing",
    quickActions: "Quick Actions",
    manageBookings: "Manage Bookings",
    availabilityCalendar: "Availability Calendar",
    createPromotion: "Create Promotion",
    verifiedProperty: "Verified Property",
    excellentRating: "Excellent rating",
    partnerSupportText:
      "Our support team is here to assist you with bookings, rooms, and account settings.",
    footerText: "TourismHub LK Partner Portal 🇱🇰",

    destinationPlaceholder: "Where are you going? Colombo, Kandy, Ella...",
    guestOption1: "2 adults · 1 room",
    guestOption2: "1 adult · 1 room",
    guestOption3: "2 adults · 2 rooms",
    guestOption4: "Family · 1 room",
    guestOption5: "Group · 3 rooms",
    destinationRequired: "Please enter a destination or hotel name",
    discoverBeautifulPlaces: "Discover Beautiful Places",
    discoverBeautifulPlacesSub:
      "Find stays near beaches, mountains, heritage cities, and more.",
    excitingOffers: "Exciting Offers",
    excitingOffersSub: "Special deals for your next Sri Lankan getaway.",
    limitedOffer: "Limited Offer",
    offerEarlyBooking: "Save up to 20% on early bookings",
    offerWeekendStay: "Get 15% off on weekend stays",
    forHotelOwners: "For hotel owners",
    listPropertyTitle: "List your property on TourismHub LK",
    listPropertySubtitle:
      "Reach more travelers, manage bookings, and grow your hotel business with our partner dashboard.",
    registerYourProperty: "Register Your Property",
  },

  si: {
    /* Common */
    help: "උදව්",
    listProperty: "ඔබගේ හෝටලය එකතු කරන්න",
    register: "ලියාපදිංචි වන්න",
    signIn: "පිවිසෙන්න",

    navHelp: "උදව්",
    navListProperty: "ඔබගේ හෝටලය එකතු කරන්න",
    navRegister: "ලියාපදිංචි වන්න",
    navSignIn: "පිවිසෙන්න",
    logout: "ඉවත් වන්න",
    home: "මුල් පිටුව",
    dashboard: "පාලක පුවරුව",
    viewAll: "සියල්ල බලන්න",
    verified: "සත්‍යාපිත",
    excellent: "විශිෂ්ටයි",
    reviews: "සමාලෝචන",
    needHelp: "උදව් අවශ්‍යද?",
    contactSupport: "සහාය අමතන්න",

    /* Search/Common Form */
    destination: "ගමනාන්තය",
    checkIn: "පැමිණීම",
    checkOut: "පිටවීම",
    guests: "අමුත්තන්",
    search: "සොයන්න",
    checkAvailability: "ලබාගත හැකිද බලන්න",

    /* Home */
    heroBadge: "සොයන්න • වෙන්කරන්න • අත්විඳින්න",
    heroTitle: "ශ්‍රී ලංකා ගමනට හෝටල් සොයා සැලසුම් කරන්න",
    heroSubtitle:
      "ගමනාන්තය හෝ හෝටල් නාමය අනුව සොයන්න. හෝටල් සසඳා වේගයෙන් වෙන්කරන්න.",
    popularDestinations: "ශ්‍රී ලංකාවේ ජනප්‍රිය ගමනාන්ත",
    popularDestinationsSub: "වැඩිම සෙවූ නගර වලින් ඔබේ ගමන ආරම්භ කරන්න.",
    exploreHotels: "හෝටල් බලන්න",
    popular: "ජනප්‍රිය",
    beach: "මුහුදු වෙරළ",
    cultural: "සංස්කෘතික",
    nature: "ස්වභාවික",
    luxury: "සුඛෝපභෝගී",
    budget: "අඩු වියදම්",
    festivals: "උත්සව",

    /* Results */
    searchResults: "සෙවීම් ප්‍රතිඵල",
    staysFound: "නවාතැන් හමු විය",
    filterBy: "පෙරහන් කරන්න",
    reset: "නැවත සකසන්න",
    priceRange: "රාත්‍රියකට මිල පරාසය",
    popularFilters: "ජනප්‍රිය පෙරහන්",
    verifiedOnly: "සත්‍යාපිත හෝටල් පමණි",
    viewDetails: "විස්තර බලන්න",
    showing: "පෙන්වමින්",
    hotels: "හෝටල්",
    sortBy: "අනුපිළිවෙල",
    recommended: "නිර්දේශිත",

    /* Hotel Details */
    overview: "සාරාංශය",
    rooms: "කාමර",
    dine: "ආහාර",
    events: "උත්සව",
    policies: "ප්‍රතිපත්ති",
    contact: "සම්බන්ධ වන්න",
    bestSeller: "ජනප්‍රිය හෝටලය",
    pendingVerification: "සත්‍යාපනය බලාපොරොත්තුවෙන්",
    reviewText: "සමාලෝචන",
    topRatedStay: "ඉහළ ඇගයීමක් ඇති නවාතැන",
    topRatedDesc: "අමුත්තන් මෙම හෝටලයේ පහසුව සහ ස්ථානයට කැමතියි.",
    payAtHotel: "හෝටලයේදී ගෙවන්න",
    payAtHotelDesc: "දැන් වෙන්කරගෙන පැමිණීමේදී ගෙවීම සම්පූර්ණ කරන්න.",
    greatLocation: "හොඳ ස්ථානයක්",
    greatLocationDesc: "ආකර්ෂණීය ස්ථාන, ආපනශාලා සහ ප්‍රවාහනයට ආසන්නයි.",
    experiencesNearHotel: "මෙම හෝටලය අසල අත්දැකීම්",
    experiencesDesc: "අසල ඇති ආකර්ෂණීය ස්ථාන සහ ක්‍රියාකාරකම් සොයාගන්න.",
    getDirections: "මාර්ගය බලන්න",
    roomsAvailability: "කාමර සහ ලබාගත හැකියාව",
    roomsAvailabilityDesc: "කාමර සහ මිල බලන්න දිනයන් තෝරන්න.",
    viewAllRooms: "සියලු කාමර බලන්න",
    facilities: "පහසුකම්",
    facilitiesDesc: "සුවපහසු නවාතැනකට අවශ්‍ය සියලු දේ.",
    reserve: "වෙන්කරන්න",
    reserveNow: "දැන් වෙන්කරන්න",
    startingFrom: "ආරම්භක මිල",
    perNight: "රාත්‍රියකට",
    perNightForTwo: "අමුත්තන් 2ක් සඳහා රාත්‍රියකට",
    policiesDesc: "වෙන්කිරීමට පෙර හෝටල් ප්‍රතිපත්ති කියවන්න.",
    cancellation: "අවලංගු කිරීම",
    cancellationDesc: "නියමිත කාලයට පෙර නොමිලේ අවලංගු කළ හැක.",
    payment: "ගෙවීම",
    paymentDesc: "ඩෙමෝ වෙන්කිරීම සඳහා හෝටලයේදී ගෙවීම ලබා ගත හැක.",
    showOnMap: "සිතියමේ පෙන්වන්න",
    noBookingFees: "වෙන්කිරීම් ගාස්තු නැත",
    payAtHotelAvailable: "හෝටලයේදී ගෙවිය හැක",
    verifiedHotelListing: "සත්‍යාපිත හෝටල් ලැයිස්තුව",
    supportText: "අපගේ සහාය කණ්ඩායම ඔබට වෙන්කිරීම් සහ හෝටල් විස්තර සඳහා උදව් කරයි.",
    selectCheckIn: "පැමිණීම තෝරන්න",
    selectCheckOut: "පිටවීම තෝරන්න",
    loadingHotel: "හෝටල් විස්තර පූරණය වෙමින්...",

    /* Login */
    loginTitle: "පිවිසෙන්න",
    loginSubtitle: "ඉදිරියට යාමට ඔබගේ ගිණුම් විස්තර ඇතුළත් කරන්න.",
    email: "ඊමේල් ලිපිනය",
    password: "මුරපදය",
    rememberMe: "මාව මතක තබා ගන්න",
    forgotPassword: "මුරපදය අමතකද?",
    createAccount: "ගිණුමක් සාදන්න",
    welcomeBack: "නැවත සාදරයෙන් පිළිගනිමු",
    loginHeroTitle: "පිවිසී ඔබගේ ශ්‍රී ලංකා ගමන දිගටම කරගෙන යන්න",
    loginHeroSubtitle:
      "ඔබගේ වෙන්කිරීම්, සුරැකි හෝටල්, සහකරු පුවරුව සහ පරිපාලන මෙවලම් එකම ආරක්ෂිත ගිණුමකින් භාවිතා කරන්න.",
    bookHotelsFaster: "හෝටල් ඉක්මනින් වෙන්කරන්න",
    loginBenefitBooking:
      "ඔබගේ සෙවීම් දිගටම කරගෙන ගොස් වෙන්කිරීම් පහසුවෙන් කළමනාකරණය කරන්න.",
    secureLogin: "ආරක්ෂිත පිවිසුම",
    secureLoginDesc: "ඔබගේ ගිණුම භූමිකා අනුව ආරක්ෂිත ප්‍රවේශයක් භාවිතා කරයි.",
    exploreSriLanka: "ශ්‍රී ලංකාව සොයා බලන්න",
    exploreSriLankaDesc: "නවාතැන්, උත්සව සහ අත්දැකීම් එකම වේදිකාවකින් සොයාගන්න.",
    enterPassword: "ඔබගේ මුරපදය ඇතුළත් කරන්න",
    hidePassword: "සඟවන්න",
    showPassword: "පෙන්වන්න",
    signingIn: "පිවිසෙමින්...",
    demoLoginGuide: "ඩෙමෝ පිවිසුම් මාර්ගෝපදේශය",
    demoLoginGuideDesc:
      "ලියාපදිංචිය හෝ Postman භාවිතයෙන් database තුළ ඇතුළත් කළ ඊමේල් සහ මුරපදය භාවිතා කරන්න.",
    doNotHaveAccount: "ගිණුමක් නැද්ද?",
    enterEmailPassword: "කරුණාකර ඊමේල් සහ මුරපදය ඇතුළත් කරන්න.",
    invalidLogin: "ඊමේල් හෝ මුරපදය වැරදියි.",
    loginSuccess: "පිවිසීම සාර්ථකයි. යොමු කරමින්...",
    serverConnectionFailed:
      "සර්වර් සම්බන්ධතාවය අසාර්ථකයි. Backend ක්‍රියාත්මකද බලන්න.",

    /* Register */
    registerTitle: "ගිණුමක් සාදන්න",
    registerSubtitle: "ආරම්භ කිරීමට ඔබගේ විස්තර පුරවන්න.",
    fullName: "සම්පූර්ණ නම",
    phone: "දුරකථන අංකය",
    confirmPassword: "මුරපදය තහවුරු කරන්න",
    tourist: "සංචාරක",
    hotelPartner: "හෝටල් සහකරු",
    createYourAccount: "ඔබගේ ගිණුම සාදන්න",
    registerHeroTitle: "TourismHub LK සමඟ එක්ව ශ්‍රී ලංකාව පහසුවෙන් සොයා බලන්න",
    registerHeroSubtitle:
      "හෝටල් වෙන්කර ගැනීමට සංචාරකයෙකු ලෙස හෝ ඔබගේ හෝටලය කළමනාකරණය කිරීමට හෝටල් සහකරුවෙකු ලෙස ලියාපදිංචි වන්න.",
    bookHotelsFasterDesc: "ශ්‍රී ලංකාවේ හෝටල් සොයා, සසඳා, වෙන්කරන්න.",
    partnerManagement: "සහකරු කළමනාකරණය",
    partnerManagementDesc: "කාමර, මිල, වෙන්කිරීම් සහ හෝටල් විස්තර කළමනාකරණය කරන්න.",
    secureAccess: "ආරක්ෂිත ප්‍රවේශය",
    secureAccessDesc: "සංචාරක, සහකරු සහ පරිපාලක සඳහා භූමිකා අනුව පිවිසුම.",
    enterFullName: "ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න",
    agreeTerms: "මම කොන්දේසි වලට එකඟ වෙමි",
    creatingAccount: "ගිණුම සාදමින්...",
    semesterDemo: "සෙමෙස්ටර් ඩෙමෝ සඳහා",
    semesterDemoDesc:
      "හෝටල් සෙවීම සඳහා සංචාරක ගිණුමක් සහ සහකරු පුවරුව සඳහා හෝටල් සහකරු ගිණුමක් සාදන්න.",
    alreadyHaveAccount: "දැනටමත් ගිණුමක් තිබේද?",
    fillAllFields: "කරුණාකර සියලුම අවශ්‍ය ක්ෂේත්‍ර පුරවන්න.",
    passwordMinLength: "මුරපදය අක්ෂර 6කට වඩා දිග විය යුතුය.",
    passwordMismatch: "මුරපද දෙක නොගැළපේ.",
    agreeTermsError: "කරුණාකර කොන්දේසි වලට එකඟ වන්න.",
    registrationFailed: "ලියාපදිංචිය අසාර්ථකයි. ඊමේල් ලිපිනය තිබිය හැක.",
    accountCreatedSuccess: "ගිණුම සාර්ථකව සාදන ලදි. පිවිසුම් පිටුවට යොමු කරමින්...",

    /* Partner Dashboard */
    partnerPortal: "සහකරු පුවරුව",
    bookings: "වෙන්කිරීම්",
    calendar: "දින දර්ශනය",
    roomsPricing: "කාමර සහ මිල",
    promotions: "ප්‍රවර්ධන",
    management: "කළමනාකරණය",
    reports: "වාර්තා",
    hotelPartnerDashboard: "හෝටල් සහකරු පාලක පුවරුව",
    partnerWelcomeText:
      "ඔබගේ හෝටලයේ සිදුවන දේ මෙතැනින් බලන්න. වෙන්කිරීම්, කාමර, පැමිණීම් සහ ලබාගත හැකියාව කළමනාකරණය කරන්න.",
    addRoom: "කාමරයක් එක් කරන්න",
    editHotel: "හෝටලය සංස්කරණය කරන්න",
    newBookings: "නව වෙන්කිරීම්",
    upcomingBookings: "ඉදිරි 3ක්",
    todayCheckIns: "අද පැමිණීම්",
    remainingCheckIns: "ඉතිරි 5ක්",
    todayCheckOuts: "අද පිටවීම්",
    allCheckedOut: "සියල්ල පිටවී ඇත",
    availabilityAlert: "ලබාගත හැකියාව අනතුරු ඇඟවීම",
    roomsNeedAttention: "කාමර අවධානයට අවශ්‍යයි",
    averageRating: "සාමාන්‍ය ඇගයීම",
    onlyOneRoomLeft: "Deluxe Room එකක් පමණක් ඉතිරිව ඇත",
    latestBookings: "නවතම වෙන්කිරීම්",
    latestBookingsDesc: "ඔබගේ නවතම හෝටල් වෙන්කිරීම් බලන්න සහ කළමනාකරණය කරන්න.",
    showAllBookings: "සියලු වෙන්කිරීම් පෙන්වන්න",
    today: "අද",
    thisWeek: "මෙම සතිය",
    thisMonth: "මෙම මාසය",
    allRooms: "සියලු කාමර",
    searchBookings: "වෙන්කිරීම් සොයන්න...",
    bookingId: "වෙන්කිරීම් අංකය",
    guest: "අමුත්තා",
    room: "කාමරය",
    dates: "දිනයන්",
    amount: "මුදල",
    status: "තත්ත්වය",
    confirmed: "තහවුරු කළ",
    pending: "බලාපොරොත්තුවෙන්",
    cancelled: "අවලංගු කළ",
    noBookingsFound: "වෙන්කිරීම් හමු නොවීය.",
    growProperty: "ඔබගේ හෝටලය වර්ධනය කරන්න",
    improveListingTitle:
      "ඔබගේ ලැයිස්තුව වැඩි දියුණු කර තවත් සංචාරකයින් ආකර්ෂණය කරන්න",
    improveListingDesc:
      "හොඳ ඡායාරූප එක් කරන්න, කාමර මිල යාවත්කාලීන කරන්න, ලබාගත හැකියාව නිවැරදිව තබා ගන්න.",
    updateListing: "ලැයිස්තුව යාවත්කාලීන කරන්න",
    quickActions: "ඉක්මන් ක්‍රියාමාර්ග",
    manageBookings: "වෙන්කිරීම් කළමනාකරණය",
    availabilityCalendar: "ලබාගත හැකියාව දින දර්ශනය",
    createPromotion: "ප්‍රවර්ධනයක් සාදන්න",
    verifiedProperty: "සත්‍යාපිත හෝටලය",
    excellentRating: "විශිෂ්ට ඇගයීම",
    partnerSupportText:
      "වෙන්කිරීම්, කාමර සහ ගිණුම් සැකසුම් සඳහා අපගේ සහාය කණ්ඩායම ඔබට උදව් කරයි.",
    footerText: "TourismHub LK සහකරු පුවරුව 🇱🇰",

    destinationPlaceholder: "ඔබ යන්නේ කොහෙද? කොළඹ, මහනුවර, ඇල්ල...",
    guestOption1: "වැඩිහිටියන් 2ක් · කාමර 1ක්",
    guestOption2: "වැඩිහිටියෙක් 1ක් · කාමර 1ක්",
    guestOption3: "වැඩිහිටියන් 2ක් · කාමර 2ක්",
    guestOption4: "පවුලක් · කාමර 1ක්",
    guestOption5: "කණ්ඩායමක් · කාමර 3ක්",
    destinationRequired: "කරුණාකර ගමනාන්තයක් හෝ හෝටල් නාමයක් ඇතුළත් කරන්න",
    discoverBeautifulPlaces: "අලංකාර ස්ථාන සොයා බලන්න",
    discoverBeautifulPlacesSub:
      "මුහුදු වෙරළ, කඳු, උරුම නගර සහ තවත් ස්ථාන අසල නවාතැන් සොයාගන්න.",
    excitingOffers: "විශේෂ දීමනා",
    excitingOffersSub: "ඔබගේ ඊළඟ ශ්‍රී ලංකා ගමන සඳහා විශේෂ දීමනා.",
    limitedOffer: "සීමිත දීමනාව",
    offerEarlyBooking: "කල්තියා වෙන්කිරීම් සඳහා 20% දක්වා ඉතිරි කරන්න",
    offerWeekendStay: "සති අන්ත නවාතැන් සඳහා 15%ක වට්ටමක් ලබාගන්න",
    forHotelOwners: "හෝටල් හිමියන් සඳහා",
    listPropertyTitle: "ඔබගේ හෝටලය TourismHub LK හි ලැයිස්තුගත කරන්න",
    listPropertySubtitle:
       "තවත් සංචාරකයින් වෙත ළඟාවී, වෙන්කිරීම් කළමනාකරණය කර, සහකරු පුවරුව සමඟ ඔබගේ හෝටල් ව්‍යාපාරය වර්ධනය කරන්න.",
    registerYourProperty: "ඔබගේ හෝටලය ලියාපදිංචි කරන්න",
  },

  ta: {
    /* Common */
    help: "உதவி",
    listProperty: "உங்கள் சொத்தை சேர்க்கவும்",
    register: "பதிவு",
    signIn: "உள்நுழை",
    navHelp: "உதவி",
    navListProperty: "உங்கள் சொத்தை சேர்க்கவும்",
    navRegister: "பதிவு",
    navSignIn: "உள்நுழை",
    logout: "வெளியேறு",
    home: "முகப்பு",
    dashboard: "டாஷ்போர்டு",
    viewAll: "அனைத்தையும் பார்க்க",
    verified: "சரிபார்க்கப்பட்டது",
    excellent: "சிறந்தது",
    reviews: "விமர்சனங்கள்",
    needHelp: "உதவி வேண்டுமா?",
    contactSupport: "உதவியை தொடர்பு கொள்ளுங்கள்",

    /* Search/Common Form */
    destination: "இடம்",
    checkIn: "வருகை",
    checkOut: "புறப்படும் நாள்",
    guests: "விருந்தினர்கள்",
    search: "தேடு",
    checkAvailability: "கிடைப்பதை பார்க்க",

    /* Home */
    heroBadge: "தேடு • பதிவு செய் • அனுபவி",
    heroTitle: "இலங்கை பயணத்திற்கான ஹோட்டல்களை கண்டுபிடிக்கவும்",
    heroSubtitle:
      "இடம் அல்லது ஹோட்டல் பெயரால் தேடுங்கள். தங்குமிடங்களை ஒப்பிட்டு விரைவாக பதிவு செய்யுங்கள்.",
    popularDestinations: "இலங்கையின் பிரபலமான இடங்கள்",
    popularDestinationsSub: "அதிகம் தேடப்படும் நகரங்களில் இருந்து தொடங்குங்கள்.",
    exploreHotels: "ஹோட்டல்கள் பார்க்க",
    popular: "பிரபலமான",
    beach: "கடற்கரை",
    cultural: "கலாச்சாரம்",
    nature: "இயற்கை",
    luxury: "ஆடம்பரம்",
    budget: "குறைந்த செலவு",
    festivals: "விழாக்கள்",

    /* Results */
    searchResults: "தேடல் முடிவுகள்",
    staysFound: "தங்குமிடங்கள் கிடைத்தன",
    filterBy: "வடிகட்டி",
    reset: "மீட்டமை",
    priceRange: "ஒரு இரவுக்கான விலை",
    popularFilters: "பிரபலமான வடிகட்டிகள்",
    verifiedOnly: "சரிபார்க்கப்பட்ட ஹோட்டல்கள் மட்டும்",
    viewDetails: "விவரங்கள்",
    showing: "காட்டுகிறது",
    hotels: "ஹோட்டல்கள்",
    sortBy: "வரிசைப்படுத்து",
    recommended: "பரிந்துரை",

    /* Hotel Details */
    overview: "மேலோட்டம்",
    rooms: "அறைகள்",
    dine: "உணவு",
    events: "நிகழ்வுகள்",
    policies: "கொள்கைகள்",
    contact: "தொடர்பு",
    bestSeller: "பிரபலமான ஹோட்டல்",
    pendingVerification: "சரிபார்ப்பு நிலுவையில்",
    reviewText: "விமர்சனங்கள்",
    topRatedStay: "உயர் மதிப்பீடு பெற்ற தங்குமிடம்",
    topRatedDesc: "விருந்தினர்கள் வசதி மற்றும் இடத்தை விரும்புகின்றனர்.",
    payAtHotel: "ஹோட்டலில் பணம் செலுத்துங்கள்",
    payAtHotelDesc: "இப்போது பதிவு செய்து வருகையில் பணம் செலுத்துங்கள்.",
    greatLocation: "சிறந்த இடம்",
    greatLocationDesc: "சுற்றுலா இடங்கள், உணவகங்கள் மற்றும் போக்குவரத்துக்கு அருகில்.",
    experiencesNearHotel: "இந்த ஹோட்டல் அருகிலுள்ள அனுபவங்கள்",
    experiencesDesc: "அருகிலுள்ள இடங்கள் மற்றும் செயல்பாடுகளை கண்டுபிடிக்கவும்.",
    getDirections: "வழி பார்க்க",
    roomsAvailability: "அறைகள் மற்றும் கிடைக்கும் நிலை",
    roomsAvailabilityDesc: "அறைகள் மற்றும் விலைகளை பார்க்க தேதிகளைத் தேர்ந்தெடுக்கவும்.",
    viewAllRooms: "அனைத்து அறைகளும்",
    facilities: "வசதிகள்",
    facilitiesDesc: "சௌகரியமான தங்குமிடத்திற்கு தேவையான அனைத்தும்.",
    reserve: "பதிவு செய்",
    reserveNow: "இப்போது பதிவு செய்",
    startingFrom: "தொடக்க விலை",
    perNight: "ஒரு இரவு",
    perNightForTwo: "2 விருந்தினர்களுக்கு ஒரு இரவு",
    policiesDesc: "பதிவு செய்வதற்கு முன் ஹோட்டல் கொள்கைகளை படிக்கவும்.",
    cancellation: "ரத்து செய்தல்",
    cancellationDesc: "தேர்ந்தெடுக்கப்பட்ட காலத்திற்கு முன் இலவசமாக ரத்து செய்யலாம்.",
    payment: "கட்டணம்",
    paymentDesc: "டெமோ பதிவிற்காக ஹோட்டலில் பணம் செலுத்தும் வசதி உள்ளது.",
    showOnMap: "வரைபடத்தில் காண்பி",
    noBookingFees: "பதிவு கட்டணம் இல்லை",
    payAtHotelAvailable: "ஹோட்டலில் பணம் செலுத்தலாம்",
    verifiedHotelListing: "சரிபார்க்கப்பட்ட ஹோட்டல் பட்டியல்",
    supportText: "பதிவுகள் மற்றும் ஹோட்டல் விவரங்களுக்கு எங்கள் குழு உதவும்.",
    selectCheckIn: "வருகை தேர்வு",
    selectCheckOut: "புறப்படும் நாள் தேர்வு",
    loadingHotel: "ஹோட்டல் விவரங்கள் ஏற்றப்படுகின்றன...",

    /* Login */
    loginTitle: "உள்நுழை",
    loginSubtitle: "தொடர உங்கள் கணக்கு விவரங்களை உள்ளிடவும்.",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    rememberMe: "என்னை நினைவில் கொள்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    createAccount: "கணக்கு உருவாக்கு",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    loginHeroTitle: "உள்நுழைந்து உங்கள் இலங்கை பயணத்தை தொடருங்கள்",
    loginHeroSubtitle:
      "உங்கள் பதிவுகள், சேமித்த ஹோட்டல்கள், பங்குதாரர் டாஷ்போர்டு மற்றும் நிர்வாக கருவிகளை ஒரே பாதுகாப்பான கணக்கில் அணுகவும்.",
    bookHotelsFaster: "ஹோட்டல்களை விரைவாக பதிவு செய்யுங்கள்",
    loginBenefitBooking: "உங்கள் தேடல்களைத் தொடரவும், பதிவுகளை எளிதாக நிர்வகிக்கவும்.",
    secureLogin: "பாதுகாப்பான உள்நுழைவு",
    secureLoginDesc: "உங்கள் கணக்கு பங்கு அடிப்படையிலான பாதுகாப்பான அணுகலைப் பயன்படுத்துகிறது.",
    exploreSriLanka: "இலங்கையை ஆராயுங்கள்",
    exploreSriLankaDesc:
      "தங்குமிடங்கள், நிகழ்வுகள் மற்றும் அனுபவங்களை ஒரே தளத்தில் கண்டறியுங்கள்.",
    enterPassword: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    hidePassword: "மறை",
    showPassword: "காட்டு",
    signingIn: "உள்நுழைகிறது...",
    demoLoginGuide: "டெமோ உள்நுழைவு வழிகாட்டி",
    demoLoginGuideDesc:
      "பதிவு அல்லது Postman மூலம் database இல் சேர்த்த மின்னஞ்சல் மற்றும் கடவுச்சொல்லைப் பயன்படுத்தவும்.",
    doNotHaveAccount: "கணக்கு இல்லையா?",
    enterEmailPassword: "மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    invalidLogin: "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறு.",
    loginSuccess: "உள்நுழைவு வெற்றிகரமாக முடிந்தது. மாற்றப்படுகிறது...",
    serverConnectionFailed:
      "சர்வருடன் இணைக்க முடியவில்லை. Backend இயங்குகிறதா என சரிபார்க்கவும்.",

    /* Register */
    registerTitle: "கணக்கு உருவாக்கு",
    registerSubtitle: "தொடங்க உங்கள் விவரங்களை நிரப்பவும்.",
    fullName: "முழு பெயர்",
    phone: "தொலைபேசி எண்",
    confirmPassword: "கடவுச்சொல் உறுதிப்படுத்து",
    tourist: "சுற்றுலாப் பயணி",
    hotelPartner: "ஹோட்டல் பங்குதாரர்",
    createYourAccount: "உங்கள் கணக்கை உருவாக்கவும்",
    registerHeroTitle: "TourismHub LK உடன் இணைந்து இலங்கையை எளிதாக ஆராயுங்கள்",
    registerHeroSubtitle:
      "ஹோட்டல்கள் பதிவு செய்ய சுற்றுலாப் பயணியாகவும், உங்கள் ஹோட்டலை நிர்வகிக்க ஹோட்டல் பங்குதாரராகவும் பதிவு செய்யுங்கள்.",
    bookHotelsFasterDesc: "இலங்கையில் ஹோட்டல்களை தேடி, ஒப்பிட்டு, பதிவு செய்யுங்கள்.",
    partnerManagement: "பங்குதாரர் மேலாண்மை",
    partnerManagementDesc: "அறைகள், விலை, பதிவுகள் மற்றும் ஹோட்டல் விவரங்களை நிர்வகிக்கவும்.",
    secureAccess: "பாதுகாப்பான அணுகல்",
    secureAccessDesc: "சுற்றுலா, பங்குதாரர் மற்றும் நிர்வாகிக்கு பங்கு அடிப்படையிலான உள்நுழைவு.",
    enterFullName: "உங்கள் முழு பெயரை உள்ளிடவும்",
    agreeTerms: "நான் விதிமுறைகளை ஏற்கிறேன்",
    creatingAccount: "கணக்கு உருவாக்கப்படுகிறது...",
    semesterDemo: "செமஸ்டர் டெமோவிற்காக",
    semesterDemoDesc:
      "ஹோட்டல் தேடலுக்கு சுற்றுலா கணக்கும், பங்குதாரர் டாஷ்போர்டுக்கு ஹோட்டல் பங்குதாரர் கணக்கும் உருவாக்கவும்.",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    fillAllFields: "தேவையான அனைத்து புலங்களையும் நிரப்பவும்.",
    passwordMinLength: "கடவுச்சொல் குறைந்தது 6 எழுத்துகளாக இருக்க வேண்டும்.",
    passwordMismatch: "கடவுச்சொற்கள் பொருந்தவில்லை.",
    agreeTermsError: "விதிமுறைகளை ஏற்கவும்.",
    registrationFailed: "பதிவு தோல்வியடைந்தது. மின்னஞ்சல் ஏற்கனவே இருக்கலாம்.",
    accountCreatedSuccess:
      "கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது. உள்நுழைவு பக்கத்திற்கு செல்கிறது...",

    /* Partner Dashboard */
    partnerPortal: "பங்குதாரர் தளம்",
    bookings: "பதிவுகள்",
    calendar: "நாட்காட்டி",
    roomsPricing: "அறைகள் மற்றும் விலை",
    promotions: "விளம்பரங்கள்",
    management: "மேலாண்மை",
    reports: "அறிக்கைகள்",
    hotelPartnerDashboard: "ஹோட்டல் பங்குதாரர் டாஷ்போர்டு",
    partnerWelcomeText:
      "உங்கள் சொத்தில் என்ன நடக்கிறது என்பதை இங்கே பார்க்கலாம். பதிவுகள், அறைகள், வருகைகள் மற்றும் கிடைப்பதை ஒரே இடத்தில் நிர்வகிக்கவும்.",
    addRoom: "அறை சேர்க்க",
    editHotel: "ஹோட்டலை திருத்து",
    newBookings: "புதிய பதிவுகள்",
    upcomingBookings: "3 வரவிருக்கின்றன",
    todayCheckIns: "இன்றைய வருகைகள்",
    remainingCheckIns: "5 மீதம்",
    todayCheckOuts: "இன்றைய புறப்பாடுகள்",
    allCheckedOut: "அனைவரும் புறப்பட்டனர்",
    availabilityAlert: "கிடைப்பது எச்சரிக்கை",
    roomsNeedAttention: "அறைகள் கவனம் தேவை",
    averageRating: "சராசரி மதிப்பீடு",
    onlyOneRoomLeft: "ஒரு Deluxe Room மட்டும் உள்ளது",
    latestBookings: "சமீபத்திய பதிவுகள்",
    latestBookingsDesc: "உங்கள் சமீபத்திய ஹோட்டல் பதிவுகளைப் பார்க்கவும் நிர்வகிக்கவும்.",
    showAllBookings: "அனைத்து பதிவுகளையும் காட்டு",
    today: "இன்று",
    thisWeek: "இந்த வாரம்",
    thisMonth: "இந்த மாதம்",
    allRooms: "அனைத்து அறைகள்",
    searchBookings: "பதிவுகளைத் தேடுங்கள்...",
    bookingId: "பதிவு ID",
    guest: "விருந்தினர்",
    room: "அறை",
    dates: "தேதிகள்",
    amount: "தொகை",
    status: "நிலை",
    confirmed: "உறுதிப்படுத்தப்பட்டது",
    pending: "நிலுவையில்",
    cancelled: "ரத்து செய்யப்பட்டது",
    noBookingsFound: "பதிவுகள் கிடைக்கவில்லை.",
    growProperty: "உங்கள் சொத்தை வளர்த்திடுங்கள்",
    improveListingTitle: "உங்கள் பட்டியலை மேம்படுத்து மேலும் பயணிகளை ஈர்க்கவும்",
    improveListingDesc:
      "சிறந்த படங்களைச் சேர்த்து, அறை விலைகளை புதுப்பித்து, கிடைப்பதை சரியாக வைத்திருக்கவும்.",
    updateListing: "பட்டியலை புதுப்பி",
    quickActions: "விரைவு செயல்கள்",
    manageBookings: "பதிவுகளை நிர்வகி",
    availabilityCalendar: "கிடைப்பது நாட்காட்டி",
    createPromotion: "விளம்பரம் உருவாக்கு",
    verifiedProperty: "சரிபார்க்கப்பட்ட சொத்து",
    excellentRating: "சிறந்த மதிப்பீடு",
    partnerSupportText:
      "பதிவுகள், அறைகள் மற்றும் கணக்கு அமைப்புகளுக்கு எங்கள் உதவி குழு உங்களுக்கு உதவும்.",
    footerText: "TourismHub LK பங்குதாரர் தளம் 🇱🇰",

    destinationPlaceholder: "நீங்கள் எங்கு செல்கிறீர்கள்? கொழும்பு, கண்டி, எல்லா...",
    guestOption1: "2 பெரியவர்கள் · 1 அறை",
    guestOption2: "1 பெரியவர் · 1 அறை",
    guestOption3: "2 பெரியவர்கள் · 2 அறைகள்",
    guestOption4: "குடும்பம் · 1 அறை",
    guestOption5: "குழு · 3 அறைகள்",
    destinationRequired: "இடம் அல்லது ஹோட்டல் பெயரை உள்ளிடவும்",
    discoverBeautifulPlaces: "அழகான இடங்களை கண்டறியுங்கள்",
    discoverBeautifulPlacesSub:
       "கடற்கரை, மலை, பாரம்பரிய நகரங்கள் மற்றும் பல இடங்களுக்கு அருகில் தங்குமிடங்களை கண்டறியுங்கள்.",
    excitingOffers: "சிறப்பு சலுகைகள்",
    excitingOffersSub: "உங்கள் அடுத்த இலங்கை பயணத்திற்கான சிறப்பு சலுகைகள்.",
    limitedOffer: "வரையறுக்கப்பட்ட சலுகை",
    offerEarlyBooking: "முன்கூட்டிய பதிவுகளுக்கு 20% வரை சேமிக்கவும்",
    offerWeekendStay: "வார இறுதி தங்குமிடங்களுக்கு 15% தள்ளுபடி பெறுங்கள்",
    forHotelOwners: "ஹோட்டல் உரிமையாளர்களுக்கு",
    listPropertyTitle: "உங்கள் சொத்தை TourismHub LK இல் பட்டியலிடுங்கள்",
    listPropertySubtitle:
       "மேலும் பயணிகளை அடையுங்கள், பதிவுகளை நிர்வகிக்கவும், பங்குதாரர் டாஷ்போர்டுடன் உங்கள் ஹோட்டல் வணிகத்தை வளர்த்திடுங்கள்.",
    registerYourProperty: "உங்கள் சொத்தை பதிவு செய்யுங்கள்",
  },
};

const currencyRates = {
  LKR: { symbol: "LKR", rate: 1 },
  USD: { symbol: "$", rate: 1 / 300 },
  EUR: { symbol: "€", rate: 1 / 325 },
  GBP: { symbol: "£", rate: 1 / 380 },
};

export function AppSettingsProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("language") || "en"
  );

  const [currency, setCurrency] = useState(
    () => localStorage.getItem("currency") || "LKR"
  );

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem("currency", currency);
  }, [currency]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const formatPrice = (lkrAmount) => {
    const amount = Number(lkrAmount || 0);
    const selected = currencyRates[currency] || currencyRates.LKR;
    const converted = amount * selected.rate;

    if (currency === "LKR") {
      return `LKR ${Math.round(converted).toLocaleString()}`;
    }

    return `${selected.symbol}${converted.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      currency,
      setCurrency,
      t,
      formatPrice,
    }),
    [language, currency]
  );

  return (
    <AppSettingsContext.Provider value={value}>
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  return useContext(AppSettingsContext);
}